import jsPDF from "jspdf";

export default function ReportButton() {

    const downloadReport = () => {

        try {

            const storedData = localStorage.getItem("dashboardData");

            if (!storedData) {

                alert("No dataset uploaded.");

                return;

            }

            const data = JSON.parse(storedData);

            const pdf = new jsPDF();

            let y = 20;

            
            // TITLE
            

            pdf.setFont("helvetica", "bold");
            pdf.setFontSize(24);

            pdf.text("OptiWise Analytics Report", 20, y);

            y += 10;

            pdf.setDrawColor(180);
            pdf.line(20, y, 190, y);

            y += 15;

            
            // DATASET INFORMATION
            

            pdf.setFontSize(18);
            pdf.setFont("helvetica", "bold");

            pdf.text("Dataset Information", 20, y);

            y += 12;

            pdf.setFont("helvetica", "normal");
            pdf.setFontSize(12);

            pdf.text(
                `Dataset Name : ${data.dataset_name || "Uploaded Dataset"}`,
                20,
                y
            );

            y += 8;

            pdf.text(
                `Total Rows : ${data.rows || 0}`,
                20,
                y
            );

            y += 8;

            pdf.text(
                `Total Columns : ${data.columns || 0}`,
                20,
                y
            );

            y += 8;

            pdf.text(
                `Missing Values : ${data.kpis?.missing_values ?? 0}`,
                20,
                y
            );

            y += 8;

            pdf.text(
                `Memory Usage : ${data.kpis?.memory_usage ?? 0} MB`,
                20,
                y
            );

            y += 18;

            
            // AI EXECUTIVE SUMMARY
            

            pdf.setFont("helvetica", "bold");
            pdf.setFontSize(18);

            pdf.text("AI Executive Summary", 20, y);

            y += 12;

            pdf.setFont("helvetica", "normal");
            pdf.setFontSize(11);

            const summary =
                data.summary || "No summary available.";

            const lines = pdf.splitTextToSize(summary, 170);

            lines.forEach((line) => {

                if (y > 280) {

                    pdf.addPage();

                    y = 20;

                }

                pdf.text(line, 20, y);

                y += 7;

            });

            
            // FOOTER
            

            pdf.setFontSize(10);

            pdf.setTextColor(120);

            pdf.text(
                "Generated by OptiWise - AI Driven Decision Intelligence System",
                20,
                288
            );

            pdf.save("OptiWise_Report.pdf");

        }

        catch (err) {

            console.error(err);

            alert("Failed to generate report.");

        }

    };

    return (

        <button

            onClick={downloadReport}

            className="
                bg-gradient-to-r
                from-yellow-800
                to-gray-600

                hover:from-gray-600
                hover:to-yellow-800

                text-white
                text-lg
                font-semibold

                px-8
                py-4

                rounded-2xl

                shadow-xl

                hover:shadow-2xl
                hover:scale-105

                transition-all
                duration-300

                cursor-pointer
            "

        >

             Download Report

        </button>

    );

}